steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_IMAGE_TAG}
      - .

images:
  - ${_IMAGE_TAG}

serviceAccount: projects/mkw-stats/serviceAccounts/ctc-cloud-builder@mkw-stats.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
